# Generated by Django 6.0.5 on 2026-05-20 05:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('subject', models.CharField(choices=[('consultation', 'Консультация'), ('partnership', 'Партнёрство'), ('nir', 'Запрос по НИР'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, unique=True, verbose_name='Термин')),
                ('definition', models.TextField(verbose_name='Определение')),
                ('source', models.CharField(blank=True, max_length=300, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Запись словаря',
                'verbose_name_plural': 'Словарь государственной службы',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('category', models.CharField(choices=[('conference', 'Конференция'), ('publication', 'Публикация'), ('seminar', 'Семинар'), ('grant', 'Грант'), ('announcement', 'Анонс'), ('other', 'Другое')], default='other', max_length=30, verbose_name='Категория')),
                ('excerpt', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Полный текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Главная новость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200, verbose_name='Заказчик')),
                ('title', models.CharField(max_length=400, verbose_name='Тема НИР')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('deadline', models.DateField(verbose_name='Срок подачи')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('review', 'На рассмотрении'), ('closed', 'Закрыт')], default='open', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запрос по НИР',
                'verbose_name_plural': 'Интегратор НИР',
                'ordering': ['deadline'],
            },
        ),
    ]
